import CTA from "../_components/modules/CTA/CTA";
import Footer from "../_components/modules/Footer/Footer";
import type { Metadata } from "next";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-manrope-medium">
                <Providers>
                    <div className="bg-gray-90 dark:bg-black-8 flex flex-col gap-16 lg:gap-20 2xl:gap-24">
                        {children}
                        <CTA />
                        <Footer />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
