import NavigationBar from "../_components/modules/NavigationBar/NavigationBar";
import CTA from "../_components/modules/CTA/CTA";
import Footer from "../_components/modules/Footer/Footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-manrope-medium bg-[#141414] flex flex-col gap-8 lg:gap-12 2xl:gap-16">
                <NavigationBar />
                {children}
                <CTA />
                <Footer />
            </body>
        </html>
    );
}
