import CTA from "../_components/modules/CTA/CTA";
import Footer from "../_components/modules/Footer/Footer";
import type { Metadata } from "next";
import Providers from "./providers";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode,
    params: {
        locale: "en" | "fa"
    }
}

const RootLayout: React.FC<Props> = ({
    children,
    params: { locale }
}) => {
    const messages = useMessages()
    return (
        <html lang={locale}>
            <body className="font-manrope-medium">
                <NextIntlClientProvider messages={messages}>
                    <Providers>
                        <div className="bg-gray-97 dark:bg-black-8 flex flex-col gap-16 lg:gap-20 2xl:gap-24">
                            {children}
                            <CTA />
                            <Footer />
                        </div>
                    </Providers>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}

export default RootLayout